# Generated by Django 4.2.10 on 2024-02-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('company', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('customer_message', models.TextField()),
                ('ip_address', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
                ('website_type', models.CharField(max_length=255)),
                ('form_type', models.CharField(max_length=255)),
                ('saved_in_gohighlevel', models.BooleanField(default=False)),
            ],
        ),
    ]
