# Generated by Django 4.2.10 on 2024-02-27 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.TextField()),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('location_id', models.TextField()),
                ('expires_in', models.DateTimeField()),
                ('json_response', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactFormData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('company', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('customer_message', models.TextField()),
                ('ip_address', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
                ('website_type', models.CharField(max_length=255)),
                ('form_type', models.CharField(max_length=255)),
                ('saved_in_gohighlevel', models.BooleanField(default=False)),
                ('contact_id', models.TextField(blank=True, null=True)),
                ('conversation_id', models.TextField(blank=True, null=True)),
                ('message_id', models.TextField(blank=True, null=True)),
                ('email_message_id', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiCallErrorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('error_type', models.TextField(blank=True, null=True)),
                ('api_token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coming_soon_website.apitoken')),
                ('contact_form_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coming_soon_website.contactformdata')),
            ],
        ),
    ]
