# Generated by Django 4.2.10 on 2024-02-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coming_soon_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.TextField()),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('json_response', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='contactformdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
