# Generated by Django 4.2.10 on 2024-02-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coming_soon_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationFormData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
