# Generated by Django 4.2.10 on 2024-02-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coming_soon_website', '0002_apitoken_alter_contactformdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='expires_in',
            field=models.DateTimeField(),
        ),
    ]
