# Generated by Django 4.2.10 on 2024-02-25 04:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coming_soon_website', '0003_alter_apitoken_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='ApiTokenRefreshLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_refresh_successful', models.BooleanField(default=False)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('api_token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coming_soon_website.apitoken')),
            ],
        ),
    ]
