# Generated by Django 4.2.10 on 2024-02-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coming_soon_website', '0005_apitoken_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformdata',
            name='contact_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactformdata',
            name='conversation_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactformdata',
            name='message_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
