# Generated by Django 4.2.10 on 2024-02-25 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coming_soon_website', '0007_contactformdata_email_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallErrorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('api_token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coming_soon_website.apitoken')),
            ],
        ),
        migrations.CreateModel(
            name='ApiTokenRefreshErrorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('api_token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coming_soon_website.apitoken')),
            ],
        ),
        migrations.DeleteModel(
            name='ApiTokenRefreshLog',
        ),
    ]
