# Generated by Django 4.2.10 on 2024-02-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coming_soon_website', '0008_apicallerrorlog_apitokenrefresherrorlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicallerrorlog',
            name='contact_form_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='coming_soon_website.contactformdata'),
            preserve_default=False,
        ),
    ]
